Ram | Completed Week 1 exercises
Bitshala/PB-cohort pull request #10
Opened 2023-11-05 06:32 UTC by Ram-lankada

1. Finite fields
2. Elliptic curves

2023-11-08 16:41 UTC, rajarshimaitra requested changes
Sorry, I couldn't understand which file is what. 

Can you keep the folder structure same as it is in the pb cohort repo here https://github.com/jimmysong/programmingbitcoin/tree/master/code-ch01?

Do not rename files. Just commit your version of the same files.

2023-11-09 06:17 UTC, Ram-lankada commented
Yes, definitely. 
I've named them for my better understanding.

2023-11-09 07:58 UTC, rajarshimaitra requested changes

2023-11-09 07:58 UTC, rajarshimaitra commented on exercises/week 1/solutions/Ram/chapter2/ecc.py
> +    def __init__(self, num, prime):
It seems you pasted the wrong `ecc.py`? This doesn't have the `Point` class. you need the ecc of ch-02..

2023-11-09 09:34 UTC, Ram-lankada commented on exercises/week 1/solutions/Ram/chapter2/ecc.py
> +    def __init__(self, num, prime):
Yeah! i've solved it now.

2023-11-10 10:40 UTC, rajarshimaitra approved these changes
ACK b841b8c73003b4a6bc93726d01e5da40090293aa

2023-11-10 10:41 UTC, merged